import type { Metadata } from "next";
// import { Figtree } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/Header";
import Providers from "../components/providers";

const figtree = localFont({
	src: [
		{
			path: "../../public/fonts/figtree/Figtree-Light.ttf",
			weight: "300",
			style: "normal",
		},
		{
			path: "../../public/fonts/figtree/Figtree-Regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../../public/fonts/figtree/Figtree-Medium.ttf",
			weight: "500",
			style: "normal",
		},
		{
			path: "../../public/fonts/figtree/Figtree-SemiBold.ttf",
			weight: "600",
			style: "normal",
		},
		{
			path: "../../public/fonts/figtree/Figtree-Bold.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "../../public/fonts/figtree/Figtree-ExtraBold.ttf",
			weight: "800",
			style: "normal",
		},
		{
			path: "../../public/fonts/figtree/Figtree-Black.ttf",
			weight: "900",
			style: "normal",
		},
	],
	variable: "--font-figtree",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Metaphilia",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${figtree.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col">
				<Header />
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
